Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,13 +42,17 @@ jobs:
 
       # Langkah 4: Latih dan Simpan Model ML
       # Menjalankan skrip Python 'train_model.py' untuk melatih model
-      - name: Train and Save ML Model
+      - name: Latih dan Simpan Model ML
         run: |
           python train_model.py
+          if [ ! -f "model/simple_linear_regression.joblib" ]; then
+            echo "Error: File model tidak ditemukan setelah pelatihan!"
+            exit 1
+          fi
 
       # Langkah 5: Upload Model yang Sudah Terlatih sebagai Artifact
       # Menyimpan file model yang sudah berhasil dilatih
-      - name: Upload Trained Model as an Artifact
+      - name: Upload Model yang Sudah Terlatih sebagai Artifact
         uses: actions/upload-artifact@v4
         with:
           name: ml-model
